apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJhcnVuYXdzZGV2b3BzIiwKICAgICAgInBhc3N3b3JkIjogIk9uZWRvd25AMTIzNCIsCiAgICAgICJlbWFpbCI6ICJhcnVuYXdzY2xvdWQ1M0BnbWFpbC5jb20iCiAgICB9CiAgfQp9Cg==
## base64 encoded data of config.json file 